name: github pages CI
on:
  push:
    branches: [ aight ]
    paths-ignore:
      - '**/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Clean public directory
      run: rm -rf public

    - name: Build
      run: hugo --theme=hugo-theme-stack

    - name: Create cname file
      run: echo 'macawls.dev' > public/CNAME

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.HUGO }}
          publish_dir: ./public